@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define ICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml
' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()
title C4 Container diagram for Raido

Person(PublicUser, "Public User", "[anonymous]")
Person(SpUser, "ServicePoint User", "[OIDC authenticated]")
Person(SpInt, "ServicePoint\nIntegration", "[api-key authenticated]")


Container(AppClient, "app-client", "Raido UI React/SPA") 
Container(PubWeb, "pub-web", "any web tech\ncurrently uses app-client") 

Container(ApiSvc, "api-svc", "Spring REST API") 
ContainerDb(db, "Database", "PostgreSQL")
 

Rel(PublicUser, PubWeb, "interact", "in browser")
Rel(SpUser, AppClient, "interact", "in browser")
Rel(AppClient, ApiSvc, "invoke")
Rel(PubWeb, ApiSvc, "invoke")
Rel(SpInt, ApiSvc, "invoke", "HTTPS")
Rel(ApiSvc, db, "read/write", "JDBC")
@enduml

